- name: Add td_agent_bit apt key
  ansible.builtin.apt_key:
    url: http://packages.fluentbit.io/fluentbit.key
    keyring: /etc/apt/trusted.gpg.d/td_agent_bit.gpg

- name: Add td_agent_bit apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.fluentbit.io/{{ ansible_lsb.id | lower }}/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main"
    filename: "td_agent_bit"

- name: Install td_agent_bit
  ansible.builtin.apt:
    name: td-agent-bit

- name: Create td_agent_bit directories
  ansible.builtin.file:
    path: "{{ td_agent_bit_var_dir }}"
    mode: "0755"
    state: directory

- name: Configure td_agent_bit
  ansible.builtin.template:
    src: td-agent-bit.conf.j2
    dest: /etc/td-agent-bit/td-agent-bit.conf
    mode: "0644"
  notify:
    - Restart td-agent-bit

- name: Enable td_agent_bit service
  ansible.builtin.systemd:
    name: td-agent-bit
    state: started
    enabled: true
