- name: Create Grafana volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - grafana-config
    - grafana-data

- name: Create Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    pull: "{{ homelab_docker_pull | default('missing') }}"

    network_mode: host

    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"

    volumes:
      - grafana-config:/etc/grafana:rw
      - grafana-data:/var/lib/grafana:rw

    comparisons:
      env: strict
      labels: strict

    image_name_mismatch: recreate

    state: started
    restart_policy: unless-stopped
