# lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
# lxc.cgroup2.devices.allow: c 226:0 rwm
# lxc.cgroup2.devices.allow: c 226:128 rwm

# https://github.com/immich-app/immich/blob/main/docker/docker-compose.yml

- name: Stat /dev/dri
  ansible.builtin.stat:
    path: /dev/dri
  register: dev_dri

- name: Assert if /dev/dri exists
  ansible.builtin.assert:
    that: dev_dri.stat.exists

- name: Create Immich volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - immich-redisdata
    - immich-pgdata
    - immich-model-cache

- name: Create Immich Redis container
  community.docker.docker_container:
    name: immich-redis
    image: docker.io/valkey/valkey:8-bookworm

    volumes:
      - immich-redisdata:/data:rw

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Create Immich Postgres container
  community.docker.docker_container:
    name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0

    env:
      POSTGRES_DB: immich
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--data-checksums'

    volumes:
      - immich-pgdata:/var/lib/postgresql/data:rw

    shm_size: 128M

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Create Immich ML container
  community.docker.docker_container:
    name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino

    env:
      # https://github.com/immich-app/immich/discussions/8880
      MACHINE_LEARNING_WORKER_TIMEOUT: "300"

    volumes:
      - immich-model-cache:/cache

    devices:
      - /dev/dri

    privileged: true

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Create Immich Server container
  community.docker.docker_container:
    name: immich-server
    image: ghcr.io/immich-app/immich-server:release

    env:
      TZ: "{{ timezone | default('UTC') }}"

      REDIS_HOSTNAME: immich-redis
      DB_HOSTNAME: immich-postgres

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/immich:/usr/src/app/upload

    devices:
      - /dev/dri

    privileged: true

    ports: "{{ immich_ports | default([]) }}"

    networks: "{{ docker_networks }}"
    comparisons: "{{ docker_comparisons }}"
    image_name_mismatch: "{{ docker_image_name_mismatch }}"
    state: "{{ docker_state }}"
    restart_policy: "{{ docker_restart_policy }}"
    pull: "{{ docker_pull }}"

- name: Register Immich container name
  ansible.builtin.set_fact:
    immich_container_name: "immich"
