- name: Disable SSH password login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: Restart sshd

- name: Fix /etc/sudoers.d permissions
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: "0750"
