- name: Create Loki volumes
  community.docker.docker_volume:
    volume_name: "{{ item }}"
  loop:
    - loki-data

- name: Create /etc/loki
  ansible.builtin.file:
    path: /etc/loki
    state: directory
    mode: "0755"

- name: Configure Loki
  ansible.builtin.template:
    src: loki.yml.j2
    dest: /etc/loki/loki.yml
    mode: "0644"
  notify: Restart loki

- name: Create Loki container
  community.docker.docker_container:
    name: loki
    image: grafana/loki:latest
    pull: "{{ homelab_docker_pull | default('missing') }}"

    network_mode: host

    volumes:
      - /etc/loki/loki.yml:/etc/loki/config.yml:ro
      - loki-data:/loki:rw

    command: -config.file=/etc/loki/config.yml

    user: 0:0

    comparisons:
      env: strict
      labels: strict

    image_name_mismatch: recreate

    state: started
    restart_policy: unless-stopped
